-- Content is deliberately abstract and non-instructional. All characters are fictional adults.
INSERT INTO trait_definitions (trait_key, display_name, category, description) VALUES
('shy','Shy','PERSONALITY','Careful with attention.'),('confident','Confident','PERSONALITY','Comfortable taking initiative.'),
('mysterious','Mysterious','PERSONALITY','Reveals little at first.'),('flirty','Flirty','PERSONALITY','Enjoys playful connection.'),
('playful','Playful','PERSONALITY','Finds fun in a moment.'),('romantic','Romantic','PERSONALITY','Values emotional closeness.'),
('reserved','Reserved','PERSONALITY','Protects personal space.'),('teasing','Teasing','PERSONALITY','Uses gentle provocation.'),
('bold','Bold','PERSONALITY','Acts with clear intent.'),('curious','Curious','PERSONALITY','Wants to understand people.'),
('adventurous','Adventurous','PERSONALITY','Open to new settings.'),('competitive','Competitive','PERSONALITY','Notices a challenge.'),
('protective','Protective','PERSONALITY','Looks after people they value.'),('independent','Independent','PERSONALITY','Keeps a strong centre.'),
('jealous','Jealous','PERSONALITY','Feels attention shifts deeply.'),('possessive','Possessive Personality','PERSONALITY','Needs clear reassurance.'),
('expressive','Emotionally Expressive','PERSONALITY','Shows feelings readily.'),('guarded','Emotionally Guarded','PERSONALITY','Reveals feeling selectively.'),
('calm','Calm','PERSONALITY','Keeps the atmosphere steady.'),('unpredictable','Unpredictable','PERSONALITY','Changes the expected rhythm.'),
('intense','Intense','PERSONALITY','Experiences chemistry strongly.'),('slow_burn','Slow Burn','PERSONALITY','Prefers gradual discovery.'),
('social','Social','PERSONALITY','Enjoys group energy.'),('private','Private','PERSONALITY','Prefers quieter connection.'),
('impulsive','Impulsive','PERSONALITY','Acts on a spark.'),('patient','Patient','PERSONALITY','Allows time for trust.'),
('risk_taking','Risk Taking','PERSONALITY','Accepts a little uncertainty.'),('observant','Observant','PERSONALITY','Reads details closely.')
ON CONFLICT (trait_key) DO NOTHING;

INSERT INTO action_definitions (action_key, display_name, description, timing_window_ms, tags) VALUES
('observe','OBSERVE','Read the room before acting.',0,'["reading"]'),('eye_contact','MAKE EYE CONTACT','Meet their glance at the right moment.',2200,'["timing","flirt"]'),
('smile','SMILE','Offer a warm signal.',1800,'["timing","flirt"]'),('approach','APPROACH','Close distance respectfully.',0,'["distance"]'),
('tease','TEASE','Try a light, responsive tease.',2400,'["timing","flirt"]'),('flirt','FLIRT','Express interest and read the reaction.',2000,'["timing","flirt"]'),
('compliment','COMPLIMENT','Notice something specific.',2500,'["timing","trust"]'),('change_topic','CHANGE TOPIC','Redirect the energy.',0,'["recovery"]'),
('move_closer','MOVE CLOSER','Test comfort with more proximity.',0,'["distance"]'),('order_drink','ORDER ANOTHER DRINK','Extend the social moment.',0,'["social"]'),
('change_location','CHANGE LOCATION','Suggest a fresh setting.',0,'["scene"]'),('invite_continue','INVITE TO CONTINUE DATE','Offer an optional next step.',0,'["private"]'),
('step_back','STEP BACK','Give the moment more space.',0,'["consent","recovery"]'),('end_date','END DATE','Leave with clarity and respect.',0,'["ending"]'),
('focus_character','FOCUS CHARACTER','Give one person your full attention.',0,'["attention"]'),('shift_attention','SHIFT ATTENTION','Change where your attention lands.',0,'["attention"]'),
('let_them_talk','LET THEM TALK','Watch the room evolve.',0,'["autonomy"]'),('director_card','TRIGGER DIRECTOR CARD','Introduce a situation, never a forced outcome.',0,'["director"]'),
('slow_down','SLOW DOWN','Lower intensity and check the mood.',0,'["consent"]'),('stop_scene','STOP SCENE','End the current private moment immediately.',0,'["consent"]')
ON CONFLICT (action_key) DO NOTHING;

INSERT INTO scenarios (id,name,description,locations,participant_min,participant_max,scene_phases,event_pool,available_actions,heat_modifier,roleplay_compatibility) VALUES
('0d0bda7e-0001-4db0-8c00-000000000001','Blind Date','Meet a fictional adult whose deeper personality is discovered through observation, timing, and reactions.','["Cafe","Rooftop Restaurant","Cocktail Lounge","Beach Bar","Hotel Lounge","Night Club","Private Dinner","Resort","Penthouse Bar"]',1,1,'["arrival","first_meeting","chemistry","decision"]','["late_arrival","shared_laugh","guarded_pause","unexpected_confidence"]','["observe","eye_contact","smile","approach","tease","flirt","compliment","change_topic","move_closer","order_drink","change_location","invite_continue","step_back","end_date"]',4,'["Mysterious Stranger","Confident Stranger","Secret Crush"]'),
('0d0bda7e-0002-4db0-8c00-000000000002','Midnight Circle','Three fictional adults reconnect at a rooftop party; alliances and attention shift naturally.','["Rooftop","Lounge","Balcony","Private Bar"]',2,5,'["arrival","group_spark","friction","after_hours"]','["alliance","jealous_glance","private_chat","music_shift"]','["observe","join","flirt","tease","focus_character","shift_attention","let_them_talk","director_card"]',2,'["VIP","Rival","Host","Unexpected Guest"]'),
('0d0bda7e-0003-4db0-8c00-000000000003','Masquerade Signals','A playful mystery at a masked rooftop event. Roles add texture without replacing personality.','["Grand Hall","Terrace","Moonlit Bar"]',1,5,'["masks_on","first_clue","reveal","choice"]','["secret_message","role_reversal","masked_dance"]','["observe","approach","flirt","tease","change_topic","start_roleplay","director_card"]',3,'["Spy","Detective","Suspect","Royal"]'),
('0d0bda7e-0004-4db0-8c00-000000000004','After Dark Lounge','A high-chemistry late lounge scene where consent and emotional clarity set every pace.','["Cocktail Lounge","Terrace","Private Lounge"]',1,3,'["warmup","chemistry","private_offer","aftermath"]','["intense_eye_contact","quiet_check_in","private_invitation"]','["observe","flirt","compliment","move_closer","invite_continue","slow_down","stop_scene"]',8,'["VIP","Mysterious Stranger","Old Flame"]')
ON CONFLICT (id) DO NOTHING;

-- Additional reusable starter scenarios. Their event/action lists are data, not Compose-specific logic.
INSERT INTO scenarios (id,name,description,locations,participant_min,participant_max,scene_phases,event_pool,available_actions,heat_modifier,roleplay_compatibility) VALUES
('e1d10000-0005-4db0-8c00-000000000005','Luxury Villa','A polished group night with private spaces and shifting alliances.','["Poolside","Terrace","Private Lounge"]',2,5,'["arrival","dinner","late_hours"]','["music_shift","private_chat","alliance"]','["join","change_music","private_moment","director_card"]',4,'["VIP","Bodyguard","Royal"]'),
('e1d10000-0006-4db0-8c00-000000000006','Vacation Resort','A warm temporary world where first impressions matter.','["Resort","Beach Bar","Poolside"]',1,5,'["check_in","sunset","night"]','["shared_activity","quiet_walk","new_arrival"]','["observe","start_activity","change_location","director_card"]',3,'["Vacation Stranger","Secret Crush"]'),
('e1d10000-0007-4db0-8c00-000000000007','Beach House','A relaxed social scene that can become emotionally complicated.','["Deck","Kitchen","Beach","Garden"]',2,5,'["arrival","shared_activity","night"]','["shared_laugh","jealous_glance","private_chat"]','["join","tease","let_them_talk","director_card"]',2,'["Rival","Old Flame"]'),
('e1d10000-0008-4db0-8c00-000000000008','Road Trip','Close quarters make attention and pacing meaningful.','["Roadside Stop","Hotel Lounge","Lookout"]',1,5,'["drive","stop","night"]','["music_shift","scenic_pause","detour"]','["change_music","change_mood","observe","director_card"]',1,'["Rival","Bodyguard"]'),
('e1d10000-0009-4db0-8c00-000000000009','Club Afterparty','High energy with clear boundaries and multiple social currents.','["Dance Floor","Lounge","Terrace"]',2,5,'["arrival","energy","wind_down"]','["attention_shift","quiet_check_in","private_invitation"]','["flirt","shift_attention","step_back","director_card"]',6,'["Celebrity","VIP","Spy"]'),
('e1d10000-0010-4db0-8c00-000000000010','Weekend Getaway','A longer story with changing locations and consequences.','["Cabin","Garden","Private Dinner","Terrace"]',1,5,'["arrival","night","next_morning","next_day"]','["shared_memory","late_talk","morning_aftermath"]','["continue_night","next_morning","next_day","change_location"]',2,'["Old Flame","Secret Crush","Vacation Stranger"]'),
('e1d10000-0011-4db0-8c00-000000000011','Mysterious Strangers','A roleplay-focused night of observation and carefully earned reveals.','["Lounge","Balcony","Private Bar"]',1,5,'["cover","clue","reveal"]','["secret_message","false_lead","role_reversal"]','["observe","start_roleplay","director_card"]',3,'["Mysterious Stranger","Spy","Double Agent"]'),
('e1d10000-0012-4db0-8c00-000000000012','Rivals at Midnight','Competition, attraction, and consent-led choices share the room.','["Rooftop","Games Room","Terrace"]',1,5,'["challenge","shift","choice"]','["challenge","shared_win","attention_shift"]','["tease","start_activity","step_back","director_card"]',3,'["Rival","Detective","Royal"]')
ON CONFLICT (id) DO NOTHING;

INSERT INTO scenario_roles (name,description) VALUES
('Mysterious Stranger','Keeps details just out of reach.'),('Confident Stranger','Makes a clear first impression.'),('Celebrity','Draws attention without owning the room.'),('VIP','Moves through the scene with poise.'),('Bodyguard','Notices every change in the room.'),('Rival','Creates a lively challenge.'),('Royal','Carries a theatrical sense of occasion.'),('Mysterious Guest','Arrives with an unanswered question.'),('Spy','Performs confidence while holding a secret.'),('Double Agent','Changes loyalties as the story develops.'),('Detective','Follows social clues.'),('Suspect','Has a story to protect.'),('Vampire','Adds gothic theatricality.'),('Hunter','Brings focused resolve.'),('Host','Shapes the night without controlling people.'),('Unexpected Guest','Shifts the social balance.'),('Vacation Stranger','Makes a fleeting night feel significant.'),('Performer','Uses charm as a stage presence.'),('Backstage Guest','Knows the hidden side of the event.'),('Neighbour','Makes the familiar suddenly charged.'),('Roommate','Knows everyday details.'),('Secret Crush','Hides feeling in plain sight.'),('Old Flame','Carries a shared history.')
ON CONFLICT (name) DO NOTHING;

INSERT INTO director_cards (card_key,display_name,description,effect) VALUES
('lights_out','LIGHTS OUT','The room dims; everyone responds in their own way.','{"mood":"mysterious"}'),('secret_message','SECRET MESSAGE','A message introduces uncertainty, not a command.','{"event":"message"}'),
('change_location','CHANGE LOCATION','The group receives a chance to move.','{"event":"location_offer"}'),('unexpected_guest','UNEXPECTED GUEST','A new presence shifts the social rhythm.','{"event":"arrival"}'),
('two_alone','TWO CHARACTERS ALONE','Two people have a moment away from the group.','{"event":"private_chat"}'),('jealousy','MOMENT OF JEALOUSY','A glance changes how someone reads attention.','{"emotion":"jealousy"}'),
('role_reversal','ROLE REVERSAL','The social script turns on its head.','{"event":"role_shift"}'),('takes_initiative','CHARACTER TAKES INITIATIVE','A character may choose to make a move.','{"event":"initiative"}'),
('hidden_secret','HIDDEN SECRET','A clue reveals something small but meaningful.','{"event":"discovery"}'),('private_invitation','PRIVATE INVITATION','An optional invitation appears if trust allows.','{"event":"private_offer"}')
ON CONFLICT (card_key) DO NOTHING;

INSERT INTO intimacy_cards (card_key,name,category,intensity,closeness,control_balance,difficulty,experimental_score,required_heat,compatibility_tags,icon_key) VALUES
('slow_dance','Slow Dance','ROMANTIC',1,5,0,1,1,45,'["romantic","slow"]','moon'),('quiet_confession','Quiet Confession','ROMANTIC',1,5,0,1,1,48,'["romantic","trust"]','heart'),
('playful_challenge','Playful Challenge','PLAYFUL',2,3,0,2,2,55,'["playful","confident"]','spark'),('shared_rhythm','Shared Rhythm','PLAYFUL',2,4,0,2,2,58,'["playful","responsive"]','wave'),
('close_embrace','Close Embrace','PASSIONATE',3,5,0,2,1,62,'["passionate","romantic"]','flame'),('midnight_promise','Midnight Promise','PASSIONATE',3,5,0,3,2,65,'["passionate","trust"]','star'),
('intense_connection','Intense Connection','INTENSE',4,4,0,3,2,72,'["intense","responsive"]','bolt'),('lead_and_follow','Lead and Follow','DYNAMIC',3,3,1,3,3,70,'["assertive","responsive"]','arrows'),
('roleplay_reveal','Roleplay Reveal','EXPERIMENTAL',3,3,0,4,4,75,'["experimental","roleplay"]','mask'),('new_discovery','New Discovery','EXPERIMENTAL',4,3,0,4,5,82,'["experimental","adventurous"]','compass')
ON CONFLICT (card_key) DO NOTHING;

INSERT INTO fantasy_categories (category_key,display_name,description) VALUES
('romantic','Romantic Fantasy','Emotional closeness and atmosphere.'),('slow_burn','Slow Burn','Discovery over time.'),('high_intensity','High Intensity','Strong mutual energy.'),('power_dynamic','Power Dynamic','Negotiated social confidence.'),('control','Control','Interest in taking initiative.'),('submission','Submission','Interest in yielding initiative.'),('experimental','Experimental','Curiosity about new narrative directions.'),('risk_thrill','Risk / Thrill','A taste for heightened fictional stakes.'),('voyeuristic','Voyeuristic Fantasy','Observing social tension.'),('exhibition','Exhibition Fantasy','Being noticed in a fictional setting.'),('jealousy','Jealousy Fantasy','Exploring attention conflicts.'),('secret_attraction','Secret Attraction','Feelings held back.'),('multiple_curiosity','Multiple-Partner Curiosity','Interest in complex group dynamics.'),('roleplay','Roleplay Fantasy','Playing a fictional role.'),('unknown_stranger','Unknown Stranger Fantasy','A connection with mystery.'),('rival_attraction','Rival Attraction','Chemistry through competition.'),('forbidden_romance','Forbidden-Romance Fantasy','A story with emotional obstacles.'),('public_private','Public vs Private Contrast','Different faces in different spaces.')
ON CONFLICT (category_key) DO NOTHING;

INSERT INTO dialogue_templates (template_key,speaker_style,text,tags)
SELECT 'line_' || n, style, text, tags::jsonb FROM (VALUES
(1,'shy','Their smile arrives a second late, but it is genuine.','["shy","flirt"]'),(2,'shy','They glance away, then meet your eyes again.','["shy","eye_contact"]'),(3,'confident','They lean in just enough to make the moment feel intentional.','["confident","flirt"]'),(4,'confident','"I was hoping you would come over," they say.','["confident","approach"]'),(5,'mysterious','"Maybe you will earn the rest of that story," they say.','["mysterious","discovery"]'),(6,'mysterious','A half-smile leaves the meaning open.','["mysterious","reaction"]'),(7,'teasing','"Careful. That sounded almost charming," they say.','["teasing","flirt"]'),(8,'teasing','They raise an eyebrow as if inviting a better answer.','["teasing","reaction"]'),(9,'romantic','The music seems to soften around the conversation.','["romantic","mood"]'),(10,'romantic','"I like that you noticed," they say quietly.','["romantic","compliment"]'),
(11,'intense','Their focus settles on you, steady and unhurried.','["intense","attention"]'),(12,'intense','The pause carries more feeling than the words.','["intense","tension"]'),(13,'playful','They laugh, then make room beside them.','["playful","invite"]'),(14,'playful','"That was a daring choice," they grin.','["playful","tease"]'),(15,'reserved','They take a moment before answering.','["reserved","trust"]'),(16,'reserved','"I appreciate you not rushing me," they say.','["reserved","consent"]'),(17,'curious','"What made you choose this place?" they ask.','["curious","scene"]'),(18,'curious','They notice the detail you thought nobody saw.','["curious","observation"]'),(19,'jealous','Their attention flickers to the other conversation.','["jealous","group"]'),(20,'jealous','"You seem popular tonight," they say, trying to sound casual.','["jealous","reaction"]'),
(21,'protective','"You okay with the noise here?" they ask.','["protective","comfort"]'),(22,'protective','They create a little room for you in the crowd.','["protective","action"]'),(23,'competitive','"That is your opening move? Interesting," they say.','["competitive","tease"]'),(24,'competitive','They turn the challenge into a playful spark.','["competitive","flirt"]'),(25,'social','They wave someone over, then keep you included.','["social","group"]'),(26,'social','The room seems brighter around their laugh.','["social","mood"]'),(27,'private','"Could we find somewhere quieter?" they ask.','["private","private_offer"]'),(28,'private','They prefer the conversation away from the crowd.','["private","location"]'),(29,'guarded','"That is a question for later," they say with a small smile.','["guarded","discovery"]'),(30,'expressive','Their face gives away their delight.','["expressive","reaction"]'),
(31,'calm','They slow the conversation into something easy.','["calm","recovery"]'),(32,'unpredictable','They change the subject with a surprising observation.','["unpredictable","scene"]'),(33,'bold','"Come on. Let us see where this goes," they say.','["bold","invite"]'),(34,'patient','"There is no rush," they say.','["patient","consent"]'),(35,'observant','They catch your hesitation and wait.','["observant","consent"]'),(36,'slow_burn','The connection grows in the spaces between lines.','["slow_burn","chemistry"]'),(37,'flirty','They hold eye contact a beat longer.','["flirty","eye_contact"]'),(38,'adventurous','"A different view might change the night," they say.','["adventurous","location"]'),(39,'independent','"I am here because I chose to be," they say.','["independent","confidence"]'),(40,'impulsive','They follow a sudden thought, then check your reaction.','["impulsive","reaction"]'),
(41,'roleplay','The role slips for a second, revealing the person underneath.','["roleplay","discovery"]'),(42,'roleplay','"My cover is convincing, right?" they tease.','["roleplay","tease"]'),(43,'group','Someone notices the look that passes between you.','["group","group"]'),(44,'group','Two conversations collide, changing the room.','["group","event"]'),(45,'recovery','They appreciate the change of topic.','["recovery","comfort"]'),(46,'recovery','The moment resets without losing its warmth.','["recovery","mood"]'),(47,'private_offer','"We could keep talking somewhere quieter—only if you want to," they say.','["private_offer","consent"]'),(48,'private_offer','The invitation is there, but there is no pressure behind it.','["private_offer","consent"]'),(49,'aftermath','The next silence feels different: warmer, more familiar.','["aftermath","relationship"]'),(50,'aftermath','Something new is understood, even if nobody names it yet.','["aftermath","discovery"]')
) AS t(n,style,text,tags)
ON CONFLICT (template_key) DO NOTHING;

